---
# Install
# - bash
# - bash-it

- name: install dependencies for bash-it
  apt:
    name: git
    state: latest
    update_cache: yes
  become: yes

- include: common_tasks/create_dir.yml dir="{{ bash_it_dir }}"

- name: download bash-it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: "{{ bash_it_dir }}"
    depth: 1

- name: install bash-it
  shell: |
    export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=
    ./install.sh --no-modify-config --silent
  args:
    chdir: "{{ bash_it_dir }}"

# vim: ft=ansible
