---
- hosts: all
  roles:
    - pre-install
    - dotfiles
    - dotfiles_local  # machine specific dotfiles
    - shell
    - bash
    - zsh
    - tmux
    - python
    - node
    - vim
    - vim-ycm
    - aria2
    - cmd
    - fonts
    - coding
    - gui-common
    - gui-tmux
    - gnome
    - multimedia
    - office
    - wine
    - gui-post-install

# vim: ft=ansible
