---
# Install GUI apps
# * Chromium
#   * uget
# * Firefox
# * Atom
# * Dropbox
# * Albert

- name: create necessary directory
  file:
    path: "{{ remote_home }}/.config/autostart"
    state: directory

# Install Chromium and related stuff
- name: add uGet repo
  apt_repository:
    repo: "ppa:plushuang-tw/uget-stable"
    state: present
    update_cache: yes
  become: yes

- name: install Chromium and related stuff
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - chromium-browser
    - chrome-gnome-shell
    - uget

# Install Firefox
- name: install Firefox and related stuff
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - firefox

# Install Atom
- name: instal Atom editor
  apt:
    deb: https://github.com/atom/atom/releases/download/v1.19.7/atom-amd64.deb
  become: yes

# Install Dropbox
- name: install Dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
  become: yes

- name: setup autostart of Dropbox
  file:
    src: /usr/share/applications/dropbox.desktop
    dest: "{{ remote_home }}/.config/autostart/dropbox.desktop"
    state: link

# Install Albert
- name: add Albert repo
  apt_repository:
    repo: ppa:nilarimogard/webupd8
    state: present
    update_cache: yes
  become: yes

- name: install Albert
  apt:
    name: albert
    state: latest
  become: yes

- name: setup autostart of Dropbox
  file:
    src: /usr/share/applications/albert.desktop
    dest: "{{ remote_home }}/.config/autostart/albert.desktop"
    state: link

# vi: ft=ansible
