---
# Install GUI apps
# * Chromium
#   * uget
# * Firefox
# * Atom
# * Dropbox
# * Albert
# * gnome-mpv
# * Git GUI
# * Transmission
# * Transmission Remote GTK
# * Rhythmbox
# * GoldenDict
# * MComix
# * SMPlayer
# * Telegram Desktop
# * Zeal
# * VirtualBox
# * Set GNOME favorite apps

- name: create necessary directory
  file:
    path: "{{ remote_home }}/.config/autostart"
    state: directory

# Install Chromium and related stuff
- name: add uGet repo
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - "ppa:plushuang-tw/uget-stable"
    - "ppa:slgobinath/uget-chrome-wrapper"

- name: install Chromium and related stuff
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - chromium-browser
    - chrome-gnome-shell
    - uget
    - uget-chrome-wrapper

# Install Firefox
- name: install Firefox and related stuff
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - firefox

# Install Atom
- name: instal Atom editor
  apt:
    deb: https://github.com/atom/atom/releases/download/v1.19.7/atom-amd64.deb
  become: yes

# Install Dropbox
- name: install dependencies for Dropbox
  apt:
    name: python-gpgme
    state: latest
    update_cache: yes
  become: yes

- name: install Dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
  become: yes

- name: setup autostart of Dropbox
  file:
    src: /usr/share/applications/dropbox.desktop
    dest: "{{ remote_home }}/.config/autostart/dropbox.desktop"
    state: link

# Install Albert
- name: add Albert repo
  apt_repository:
    repo: ppa:nilarimogard/webupd8
    state: present
    update_cache: yes
  become: yes

- name: install Albert
  apt:
    name: albert
    state: latest
  become: yes

- name: setup autostart of Dropbox
  file:
    src: /usr/share/applications/albert.desktop
    dest: "{{ remote_home }}/.config/autostart/albert.desktop"
    state: link

- name: install Git GUI
  apt:
    name: gitk
    state: latest
    update_cache: yes
  become: yes

# Install gnome-mpv
- name: add PPA of gnome-mpv
  apt_repository:
    repo: ppa:xuzhen666/gnome-mpv
    state: present
    update_cache: yes
  become: yes

- name: Install gnome-mpv
  apt:
    name: gnome-mpv
    state: latest
  become: yes

# Install Transmission
- name: install Transmission
  apt:
    name: transmission
    state: latest
    update_cache: yes
  become: yes

# Install Transmission Remote GTK
- name: install Transmission Remote GTK
  apt:
    name: transmission-remote-gtk
    state: latest
    update_cache: yes
  become: yes

# Install and Configure Rhythmbox
- name: install Rhythmbox
  apt:
    name: rhythmbox
    state: latest
    update_cache: yes
  become: yes

- name: configure Rhythmbox (Phase 1)
  command: dbus-launch gsettings set {{ item.schema }} {{ item.key }} {{ item.value }}
  with_items: "{{ rhythmbox_settings }}"

- name: configure Rhythmbox (Phase 2)
  script: common_files/gsettings_array.sh add
    org.gnome.rhythmbox.rhythmdb
    locations
    file://{{ remote_home }}/Music/mp3_files

- name: download Rhythmbox playlists import and export plugin
  git:
    repo: https://github.com/petko10/rhythmbox-plugin-playlists-import-export
    dest: "{{ user_local_src_dir }}/rhythmbox-plugin-playlists-import-export"

- name: install dependencies for the plugin
  apt:
    name: gir1.2-gconf-2.0
    state: latest
    update_cache: yes
  become: yes

- name: install the plugin (Phase 1)
  shell: |
    SCRIPT_PATH="{{ user_local_src_dir }}/rhythmbox-plugin-playlists-import-export/"
    PLUGIN_PATH="${HOME}/.local/share/rhythmbox/plugins/playlists_ie/"
    mkdir -p $PLUGIN_PATH
    cp -r "${SCRIPT_PATH}"* "$PLUGIN_PATH"
    rm "${PLUGIN_PATH}install.sh"

- name: install the plugin (Phase 2)
  shell: |
    PLUGIN_PATH="{{ remote_home }}/.local/share/rhythmbox/plugins/playlists_ie/"
    GLIB_SCHEME="org.gnome.rhythmbox.plugins.playlists_ie.gschema.xml"
    GLIB_DIR="/usr/share/glib-2.0/schemas/"
    cp "${PLUGIN_PATH}${GLIB_SCHEME}" "$GLIB_DIR"
    glib-compile-schemas "$GLIB_DIR"
  become: yes

- name: enable the plugin in Rhythmbox
  script: common_files/gsettings_array.sh add
    org.gnome.rhythmbox.plugins
    active-plugins
    playlists_ie

- name: configure the plugin
  command: dbus-launch gsettings set
    org.gnome.rhythmbox.plugins.playlists_ie
    ie-folder
    {{ remote_home }}/Music/playlists/rhythmbox

# Install GoldenDict
- name: install GoldenDict
  apt:
    name: goldendict
    state: latest
    update_cache: yes
  become: yes

# Install MComix
- name: install dependencies for MComix
  apt:
    name: unrar
    state: latest
  become: yes

- name: install MComix
  apt:
    name: mcomix
    state: latest
    update_cache: yes
  become: yes

# Install SMPlayer
- name: add SMPlayer PPA
  apt_repository:
    repo: ppa:rvm/smplayer
    state: present
    update_cache: yes
  become: yes

- name: install SMPlayer
  apt:
    name: smplayer
    state: latest
  become: yes

# Install Telegram Desktop
- name: add Telegram Desktop PPA
  apt_repository:
    repo: ppa:atareao/telegram
    state: present
    update_cache: yes
  become: yes

- name: install Telegram Desktop
  apt:
    name: telegram
    state: latest
  become: yes

# Install Zeal
- name: install Zeal
  apt:
    name: zeal
    state: latest
  become: yes

# Install VirtualBox
- name: install VirtualBox
  apt:
    name: virtualbox
    state: latest
  become: yes

# Set favorite apps in GNOME
- name: set favorite apps in GNOME
  script: common_files/gsettings_array.sh set
    org.gnome.shell
    favorite-apps
    {{ gnome_favorite_apps|join(' ') }}

# vi: ft=ansible
