---
# Install pyenv and some pip packages

# Install pyenv
- name: install dependencies for pyenv
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
  become: yes

- include: common_tasks/create_dir.yml dir="{{ pyenv_dir }}"

- name: install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_dir }}"

- name: install Python 2
  shell: pyenv install -s {{ py2_version }}
  args:
    executable: /bin/bash

- name: install Python 3
  shell: pyenv install -s {{ py3_version }}
  args:
    executable: /bin/bash

- name: set Python 3 as the global version
  shell: pyenv global {{ py3_version }}
  args:
    executable: /bin/bash

- name: install pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_dir }}/plugins/pyenv-virtualenv"

# Install some necessary Python packages
- name: install Python 2 packages
  pip:
    name: "{{ item }}"
    executable: "{{ pyenv_dir }}/versions/{{ py2_version }}/bin/pip"
  with_items: "{{ py2_packages }}"

- name: install Python 3 packages
  pip:
    name: "{{ item }}"
    executable: "{{ pyenv_dir }}/versions/{{ py3_version }}/bin/pip"
  with_items: "{{ py3_packages }}"

# vim: ft=ansible
