---
# Install GNOME-related softwares and configure it
# * pop-theme, and enable the themes in GNOME
# * folder-color
# * Tweak Tool
# * dconf Editor
# * extra/official GNOME shell extensions
#   * clipboard-indicator
#   * OpenWeather
#   - TopIcons-plus
# * solarized theme for GNOME Terminal
# * Install and Configure gedit
# * xclip, X selctions
# * Disable lid switch (laptop)
# * Set up input sources
#   * Install Rime input method
# * Set extra GNOME settings

# Install pop-theme
- name: add pop-theme PPA
  apt_repository:
    repo: "ppa:system76/pop"
    state: present
    update_cache: yes
  become: yes

- name: install pop-theme
  apt:
    name: pop-theme
    state: latest
  become: yes

# Enable pop-theme, a trick (dbus-launch) to change gsettings through ssh
- name: set GTK, Icon and Cursor themes
  command: dbus-launch gsettings set {{ item }}
  with_items:
    # GTK theme
    - org.gnome.desktop.interface gtk-theme Pop-dark
    # Icon theme
    - org.gnome.desktop.interface icon-theme Pop
    # Cursor theme
    - org.gnome.desktop.interface cursor-theme Pop

# Prepare extension enabling script
- name: create temporary directory for extension enabling script
  tempfile:
    state: directory
  register: tempdir_ret

- name: copy the script to the remote
  copy:
    src: enable-gnome-shell-extension.sh
    dest: "{{ tempdir_ret.path }}"
    mode: u+x
  register: copy_ret

- name: make the script file path global
  set_fact:
    gnome_shell_ext_enable_script: "{{ copy_ret.dest }}"

- name: enable user-theme extension
  command: dbus-launch "{{ gnome_shell_ext_enable_script }}"
    'user-theme@gnome-shell-extensions.gcampax.github.com'

# Install/Enable official extensions
- name: install official shell extensions
  apt:
    name: gnome-shell-extensions
    state: latest
  become: yes

- name: enable official shell extensions
  command: dbus-launch "{{ gnome_shell_ext_enable_script }}" "{{ item }}"
  with_items: "{{ official_gnome_shell_extensions }}"

# Enable pop Shell theme
- name: set Shell theme
  command: dbus-launch gsettings set org.gnome.shell.extensions.user-theme name Pop-dark

# Install GNOME tweak tool and dconf-editor
- name: install GNOME Tweak Tool and dconf Editor
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - gnome-tweak-tool
    - dconf-editor

# Install Folder Color
- name: add Folder Color PPA
  apt_repository:
    repo: ppa:costales/folder-color
    state: present
    update_cache: yes
  become: yes

- name: install Folder Color
  apt:
    name: folder-color
    state: latest
  become: yes

# Install/Enable clipboard-indicator extension
- name: install clipboard-indicator extension
  git:
    repo: "https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator.git"
    dest: "{{ gnome_shell_extensions_dir }}/clipboard-indicator@tudmotu.com"

- name: enable clipboard-indicator extension
  command: dbus-launch "{{ gnome_shell_ext_enable_script }}"
    "clipboard-indicator@tudmotu.com"

# Install/Enable weather extension
- name: install gnome-shell-extension-weather
  apt:
    name: gnome-shell-extension-weather
    state: latest
    update_cache: yes
  become: yes

- name: enable gnome-shell-extension-weather
  command: dbus-launch "{{ gnome_shell_ext_enable_script }}"
    "openweather-extension@jenslody.de"

# Install solarized theme for GNOME Terminal
- name: install dependencies for GNOME Terminal profile
  apt:
    name: dconf-cli
    state: latest
    update_cache: yes
  become: yes

## create a solarized profile
- name: create temporary directory for the script to
    create GNOME Terminal profile 'solarized' and set it as default
  tempfile:
    state: directory
  register: tempdir_ret

- name: copy the script to the remote
  copy:
    src: create-gnome-terminal-profile-and-set-default.sh
    dest: "{{ tempdir_ret.path }}"
    mode: u+x
  register: copy_ret

- name: run the script
  command: dbus-launch "{{ copy_ret.dest }}"

## Install the theme
- name: get gnome-terminal-colors-solarized repo
  git:
    repo: https://github.com/Anthony25/gnome-terminal-colors-solarized
    dest: "{{ user_local_src_dir }}/gnome-terminal-colors-solarized"

- name: install gnome-terminal-colors-solarized
  command: dbus-launch ./install.sh -s dark -p solarized --skip-dircolors
  args:
    chdir: "{{ user_local_src_dir }}/gnome-terminal-colors-solarized"

# Install gedit
- name: install gedit
  apt:
    name: gedit
    state: latest
    update_cache: yes
  become: yes

- name: configure gedit  # make sure user not logged in GUI, or it won't work
  command: dbus-launch gsettings set org.gnome.gedit.preferences.editor
    {{ item.key }} {{ item.value }}
  with_items: "{{ gedit_preferences }}"

# Install xclip
- name: install xclip
  apt:
    name: xclip
    state: latest
    update_cache: yes
  become: yes

# Disable lid switch
- name: disable lid switch handle
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#HandleLidSwitch='
    line: 'HandleLidSwitch=ignore'
  become: yes

# Set up input sources
- name: install Rime input method
  apt:
    name: ibus-rime
    state: latest
    update_cache: yes
  become: yes

- name: add Rime to input sources
  script: common_files/gsettings_array.sh add
    org.gnome.desktop.input-sources
    sources
    "('ibus', 'rime')"

- name: set input method settings in GSettings
  command: dbus-launch gsettings set {{ item.schema }} {{ item.key }} {{ item.value }}
  with_items: "{{ input_sources_settings }}"

# Set extra GNOME settings
- name: set extra GNOME settings
  command: dbus-launch gsettings set {{ item.schema }} {{ item.key }} {{ item.value }}
  with_items: "{{ extra_gnome_settings }}"

# vi: ft=ansible
