---
# Install CLI utilites
# - bd
# - ack, beyond grep
# - thefuck, corrects your command
# - tree
# - sshfs
# - samba-common
# - parallel
# - 7zip
# - mediainfo
# - cowsay & lolcat
# - lame
# - speed-test

# Update apt cache
- name: update apt cache
  apt:
    update-cache: yes
  become: yes

# Install bd
- name: install bd
  get_url:
    url: https://raw.github.com/vigneshwaranr/bd/master/bd
    dest: /usr/local/bin/bd
    mode: 0755
  become: yes

- name: install bash completion for bd
  get_url:
    url: https://raw.github.com/vigneshwaranr/bd/master/bash_completion.d/bd
    dest: /etc/bash_completion.d/bd
  become: yes

# Install ack
- name: install ack
  get_url:
    url: https://beyondgrep.com/ack-2.22-single-file
    dest: /usr/bin/ack
    mode: 0755
  become: yes

# Install thefuck
- name: install dependencies for thefuck
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python3-pip
    - python3-dev

- name: install thefuck
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  become: yes
  with_items:
    - psutil
    - thefuck

# Install tree
- name: install tree
  apt:
    name: tree
    state: latest
  become: yes

# Install sshfs and samba-common
- name: install sshfs, samba-common
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - sshfs
    - samba-common

# Install parallel
- name: install parallel
  apt:
    name: parallel
    state: latest
  become: yes

# Install 7zip
- name: install 7zip
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - p7zip-full
    - p7zip-rar

# Install mediainfo
- name: install mediainfo
  apt:
    name: mediainfo
    state: latest
  become: yes

# Install cowsay & lolcat
- name: install cowsay & lolcat
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - cowsay
    - lolcat

# Install lame
- name: install lame
  apt:
    name: lame
    state: latest
  become: yes

# Install speed-test
- name: install speed-test
  npm:
    name: speed-test
    state: latest
    global: yes
  become: yes

# vim: ft=ansible
