---
# Install
# - tmux
# - tpm to manage plugins
# - tmuxifier
# - desktop file for GNOME and tmux

# Install tmux
- name: install tmux
  apt:
    name: tmux
    state: latest
    update-cache: yes
  become: yes

# Install tpm
- name: install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tpm_dir }}"

# Install tmuxifier
- name: install tmuxifier
  git:
    repo: https://github.com/jimeh/tmuxifier.git
    dest: "{{ tmuxifier_dir }}"

# Create a desktop file for tmux and GNOME
- name: create a desktop file for tmux
  template:
    src: tmux-gnome-terminal.desktop.j2
    dest: "{{ remote_home }}/.local/share/applications/tmux-gnome-terminal.desktop"

# vim: ft=ansible
