---
# Install NodeJS
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - git
    - curl

- name: add repo for NodeJS 8
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

- name: install NodeJS 8
  apt:
    name: nodejs
    state: latest
  become: yes

# Install NodeJS packages
- name: install npm package speed-test
  npm:
    name: speed-test
    state: latest
    global: yes
  become: yes

# vim: ft=ansible
