---
# Create a desktop file for tmux and GNOME
- name: create a desktop file for tmux
  template:
    src: tmux-gnome-terminal.desktop.j2
    dest: "{{ remote_home }}/.local/share/applications/tmux-gnome-terminal.desktop"

# vim: ft=ansible
