---
# Install
# * Vim
# * vim-plug and use it to install plugins
# * apps required by plugins
# * Syntastic checkers
#   * mdl, markdown
#   * ShellCheck, shell script
#   * flake8, for Python
#   * eslint, for HTML and Javascript
#   * vint, for Vim script

- name: install vim
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: true
  with_items:
    - vim
    - vim-gtk  # need this to support system clipboard in X11

- include_tasks: common_tasks/create_dir.yml dir="{{ vim_dir }}"

- name: create directory for vim-plug
  file:
    path: "{{ vim_dir }}/autoload"
    state: directory

# Vim plugins are listed in dotfiles
- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_dir }}/autoload/plug.vim"

- name: install dependencies for vim plugins
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ vim_dependencies }}"
  become: yes

- name: install vim plugins
  command: vim -c PlugUpdate -c quitall

# Install Syntastic checkers
- name: install dependencies of Syntastic checkers
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - ruby  # required by mdl

## mdl
- name: install markdown lint tool, mdl
  gem:
    name: mdl
    state: latest
    user_install: no
  become: yes

## ShellCheck
- name: install shellcheck
  apt:
    name: shellcheck
    state: latest
    update_cache: yes
  become: yes

## flake8
- name: install flake8
  apt:
    name: flake8
    state: latest
  become: yes

## eslint
- name: install eslint
  npm:
    name: eslint
    state: latest
    global: yes
  become: yes

## vint
- name: install dependencies for vint
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python3-pip

- name: install vint
  pip:
    name: vim-vint
    executable: /usr/bin/pip3
  become: yes

# vim: ft=ansible
