---
# Install
# - latest aria2
# - diana, aria2 cmd interface

# Install aria2
- name: install aria2
  apt:
    name: aria2
    state: latest
  become: yes

# Create config dir
- include_tasks: common_tasks/create_dir.yml dir="{{ aria2_config_dir }}"

# Generate secret token
- include_tasks: common_tasks/gen_random_string.yml

# aria2 daemon for current user
- name: set up systemd unit for aria2 on current user
  template:
    src: aria2.service.j2
    dest: "{{ systemd_user_dir }}/aria2.service"
  vars:
    secret_token: "{{ random_str_ret.stdout }}"

# autostart aria2 daemon
- name: start and upstart aria2 daemon
  systemd:
    user: yes
    name: aria2
    daemon_reload: yes
    enabled: yes
    state: restarted

# Install diana
- name: download diana
  git:
    repo: https://github.com/baskerville/diana
    dest: "{{ diana_dir }}"

- name: install diana
  file:
    src: "{{ diana_dir }}/diana"
    dest: "{{ user_local_bin_dir }}/diana"
    state: link

- name: install dad (from diana)
  file:
    src: "{{ diana_dir }}/dad"
    dest: "{{ user_local_bin_dir }}/dad"
    state: link

# Token for diana, secrets file correctly set by dotfiles
- name: set the token for diana (aria2 cmd interface)
  lineinfile:
    path: "{{ aria2_secret_file }}"
    create: yes
    regexp: '^export DIANA_SECRET_TOKEN='
    line: "export DIANA_SECRET_TOKEN={{ random_str_ret.stdout }}"

# vim: ft=ansible
