---
# Install Google Noto fonts, including CJK and Emoji

- name: install required packages for installing fonts
  apt:
    name: unzip
    state: latest
    update_cache: yes
  become: yes

# Install most of them from packages
- name: install Google Noto fonts
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - fonts-noto
    - fonts-noto-cjk
  become: yes

# Install Noto fonts
- name: create a temporary directory for Noto fonts
  tempfile:
    state: directory
  register: tempdir_ret

- name: download Noto fonts
  unarchive:
    src: https://noto-website.storage.googleapis.com/pkgs/{{ item }}.zip
    dest: "{{ tempdir_ret.path }}"
    remote_src: yes
  with_items:
    - NotoColorEmoji-unhinted
    - NotoEmoji-unhinted
    - NotoSerifCJKsc-hinted

- name: create directories for fonts
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/share/fonts/truetype/noto
    - /usr/share/fonts/opentype/noto
  become: yes

- name: find truetype Noto fonts
  find:
    paths: "{{ tempdir_ret.path }}"
    patterns: "*.ttf"
    recurse: yes
  register: find_ttf_ret

- name: install truetype Noto fonts
  copy:
    src: "{{ item.path }}"
    dest: /usr/share/fonts/truetype/noto
    remote_src: yes
  with_items: "{{ find_ttf_ret.files }}"
  become: yes
  notify: update font cache

- name: find opentype Noto fonts
  find:
    paths: "{{ tempdir_ret.path }}"
    patterns: "*.otf"
    recurse: yes
  register: find_otf_ret

- name: install opentype Noto fonts
  copy:
    src: "{{ item.path }}"
    dest: /usr/share/fonts/opentype/noto
    remote_src: yes
  with_items: "{{ find_otf_ret.files }}"
  become: yes
  notify: update font cache

# vi: ft=ansible
